# Generated by Django 4.1.4 on 2022-12-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_usersubmitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmitted',
            name='rightans',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
