# Generated by Django 4.1.4 on 2022-12-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_alter_usersubmitted_rightans'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizcategory',
            name='submit',
            field=models.BooleanField(default=False),
        ),
    ]
