# Generated by Django 4.1.4 on 2022-12-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_quizcategory_submit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='opt_1',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='opt_2',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='opt_3',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='opt_4',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='opt_ans',
            field=models.TextField(max_length=200),
        ),
    ]
