# Generated by Django 4.1.4 on 2022-12-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0006_alter_quizquestion_opt_1_alter_quizquestion_opt_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmitted',
            name='rightans',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
